services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: tech-memo-sqlserver
    environment:
      SA_PASSWORD: "Test@1234"
      ACCEPT_EULA: "Y"
      MSSQL_DB: tech_memo
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
